### ISSUE TITLE
Show all overloads of Constructor

### ISSUE THREAD

**Issue by AizazZaidee** [MrJul/ReSharper.EnhancedTooltip#155] opened 2020-01-17 09:58 UTC
Thanks a lot for making it easier to develop with C#. I don't know what I would do if there was no Resharper.

I would like to see all the overloads of the constructor. There should be an option to expand and see the Constructors parameters and doc not just number like "+2 Overloads"

Thanks.

**Comment by MrJul** [comment] 2020-04-27 15:47
The number of candidates can be huge. Enhanced Tooltip or ReSharper only displays the currently resolved overload in the standard tooltip, by design.

However you can still invoke the signature tooltip selector on a method and use the keyboard up/down arrows to view all overloads.

I'm going to close this as by design.

**Closed by MrJul** 2020-04-27 15:47 UTC
