### ISSUE TITLE
2023.1 EAP Exception

### ISSUE THREAD

**Issue by Mike-E-angelo** [MrJul/ReSharper.EnhancedTooltip#177] opened 2023-02-14 12:59 UTC
Wanted to make sure you are aware of an exception identified in the latest EAP:
https://youtrack.jetbrains.com/issue/RSRP-491292/2023.1-EAP4-No-Intellisense-After-Unknown-Activity#focus=Comments-27-6867347.0-0

Thank you for any consideration. 🙏

**Comment by DimitarCC** [comment] 2023-02-14 13:07
Thanks for pointing me out to this. But if i understood correctly it happens on recent R# EAP and not in RTM version.
So, in my opinion we can wait for RTM to be released and then see what is going on. I think the problem is in SDK differences.
Correct me if i am wrong.

**Comment by Mike-E-angelo** [comment] 2023-02-14 14:46
Good question @DimitarCC I will allow @sergeyQx to confirm :D

**Comment by sergeyQx** [comment] 2023-02-14 15:52
Given ReSharper reached feature freeze stage, I would not expect any API changes after this point.

**Comment by sergeyQx** [comment] 2023-02-16 10:07
There are several issues mentioned in that YouTrack ticket.

- Potential performance problem: https://youtrack.jetbrains.com/issue/RSRP-491292/2023.1-EAP4-No-Intellisense-After-Unknown-Activity#focus=Comments-27-6867353.0-0
- And an exception https://youtrack.jetbrains.com/issue/RSRP-491292/2023.1-EAP4-No-Intellisense-After-Unknown-Activity#focus=Comments-27-6867347.0-0

**Comment by DimitarCC** [comment] 2023-02-16 10:53
Thank you for the info. The performance issue because of using UI thread is known. But it requires complete rewrite of the extension to support async.
In my opinion that will break compatibility with older visual studio before 2019. Am i right @sergeyQx?

I may prepare a prerelease version of EnhancedTooltip. But i was thinking to wait until R# 2023.1 is released RTM

**Comment by sergeyQx** [comment] 2023-02-16 12:07
I will ask my colleague to comment on the UI thread issue. Thanks for looking into this

**Comment by sirduke** [comment] 2023-02-16 14:33
Hi @DimitarCC ,
you can use `InterruptableReadActivity` to remove the call to `TryGetTooltip` from the main thread. The approach can be like:
1. Create instance of `System.Windows.Controls.ContentPresenter` with visibility `Visibility.Collapsed` as a placeholder for the future tooltip
2. Create an activity inherrited from `InterruptableReadActivity` which calls `TryGetTooltip` and does other staff in its `Work` method and adds created content to the `ContentPresenter` from (1) in its `Finish` method
3. Use `ContentPresenter` from (1) as tooltip's content in `quickInfoContent`


```
public class MyContentPresenter: ContentPresenter
{
  public MyContentPresenter() { Visibility = Visibility.Collapsed;}
  public void SetContent(RichTextBlock content) {
    Content = content;
    Visibility = Visibility.Viisible;
  }
}

public class MyInterruptableReadActivity : InterruptableReadActivity 
{
  public MyInterruptableReadActivity(MyContentPresenter presenter, IHighlighter highlighter) ...
  
  protected override void Work() {
    myRichTextBlock = myHighlihgter.TryGetTooltip(HighlighterTooltipKind.TextEditor);
    myHighlihgter = null;
  }

  protected override void Finish()
  {
    myPresenter.SetContent(myRichTextBlock);
  }
}

...
public void AugmentQuickInfoSession(... , IList<object> quickInfoContent,...)
{
  ...
  var presenter = new MyContentPresenter();
  var activity = new MyInterruptableReadActivity(presenter, highlighter);
  activity.DoStart();
  quickInfoContent.Add(presenter);
  ...
}
```

**Comment by DimitarCC** [comment] 2023-02-16 14:52
Thanks for the tip @sirduke . I will try to implement that as soon as possible.

**Comment by DimitarCC** [comment] 2023-02-16 15:50
@sirduke  InterruptableReadActivity requires lifetime in the constructor... What should be supplied there since in Infosource class i have no access to lifetime object of any kind?

**Comment by DimitarCC** [comment] 2023-02-16 16:19
@sirduke thank you!!! A sample will be very helpful.

**Comment by sirduke** [comment] 2023-02-17 07:45
@DimitarCC 
you can make something like this. Every invocation of `NextLifetime` cancels previous lifetime, so you need to call it once per  `AugmentQuickInfoSession`
```
[ShellComponent]
public class QuickInfoSessionsLifetimes {
	private SequentialLifetimes SequentialLifetimes { get; }
	public QuickInfoSessionsLifetimes(Lifetime lifetime) {
		SequentialLifetimes = new SequentialLifetimes(lifetime);
	}
	public Lifetime NextLifetime(ITextControl textControl) {
		return SequentialLifetimes.Next().Intersect(textControl.Lifetime);
	}
}

**Comment by DimitarCC** [comment] 2023-02-17 07:48
Thank you very much @sirduke. I will try it. The call in Enhanced tooltip and complex right now and all this to be implemented may require a complete rewrite by using complete different workflow. But i will try :). Thank again.

**Comment by DimitarCC** [comment] 2023-03-29 12:19
The part with the exception because of the new SDK is fixed. A prerelease version is awaiting approval now.
Still left is the problem with UI thread. But that requires a complete rewrite of the extension. So it will take time.

**Comment by rizi** [comment] 2023-04-12 04:50
> The part with the exception because of the new SDK is fixed. A prerelease version is awaiting approval now. Still left is the problem with UI thread. But that requires a complete rewrite of the extension. So it will take time.

@DimitarCC a new version shows up (is this the prerelease version you mentioned above?), is it safe to intall it or should we wait until a new version is published (I'm asking because of the "problem with UI thread")?

br & thx for your work!

**Comment by DimitarCC** [comment] 2023-04-12 05:41
@rizi  Its not the prerelease version. The version you see now is the final for SDK 2023.1.0.
The problem with UI thread will stay long time. But it is safe to use since it was working like that till now.
It is however recommended that to be fixed at some point.
However you can use the extension.

**Comment by DimitarCC** [comment] 2023-08-18 05:16
I close this and open a new issue that will be only for async problem

**Closed by DimitarCC** 2023-08-18 05:16 UTC
