### ISSUE TITLE
Support for C# 7 Local Functions

### ISSUE THREAD

**Issue by mteknight** [MrJul/ReSharper.EnhancedTooltip#128] opened 2018-04-12 12:45 UTC
Related to #105 

I'm using latest version now and can see that the tooltip is the default Visual Studio 2017 (15.6.6):

![image](https://user-images.githubusercontent.com/7735226/38677836-b702832c-3e5f-11e8-9536-4dacce9d91b5.png)

For all other methods it works correctly:

![image](https://user-images.githubusercontent.com/7735226/38677944-02687268-3e60-11e8-8213-b15588c5961a.png)

**Comment by MrJul** [comment] 2018-04-17 11:35
I can't seem to reproduce this (even typed the exact same code as your screenshot), local functions have been supported for a while. Is something else interacting here?

**Comment by mteknight** [comment] 2018-04-18 11:52
Not sure. I do have plugins, but none that touches tooltips. Besides, I tried a clean install with default vs 2017 Enterprise installation + Resharper, the same issue.

**Comment by MrJul** [comment] 2020-04-27 15:34
Closing as I can't reproduce. Feel free to reopen if needed!

**Closed by MrJul** 2020-04-27 15:34 UTC
Labels: bug
