### ISSUE TITLE
Installation in 2019.1.1 Throws Exceptions During Install

### ISSUE THREAD

**Issue by Mike-EEE** [MrJul/ReSharper.EnhancedTooltip#147] opened 2019-05-17 20:43 UTC
FWIW this extension causes exceptions to be thrown during install on 2019.1.1:

https://youtrack.jetbrains.com/issue/RSRP-474612

The other extension listed in the report was fixed.  Perhaps @matkoch can assist here and let you know what needs to be addressed. :)

**Comment by MrJul** [comment] 2019-05-18 00:21
Unfortunately there's not much I can do :(

I'm going to close this as a duplicate of #102.
Please see https://youtrack.jetbrains.com/issue/RSRP-463582 for the R# issue, and https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/102#issuecomment-384885954 for a workaround.

**Closed by MrJul** 2019-05-18 00:21 UTC

**Comment by Mike-EEE** [comment] 2019-05-18 03:22
Ok cool!  I did see the 2017 but was too lazy to see that it might be related. 😇 Thank you for being responsive and helpful here.  I will update the 2019 issue to let them know that it is related. 👍

**Comment by Mike-EEE** [comment] 2019-05-18 03:59
Confirming here that it worked... thanks again!

FWIW, for VS2019 there are additional files to copy.  Here is the full list that made the errors go away for me:

1. `Microsoft.VisualStudio.Text.Data.dll`
1. `Microsoft.VisualStudio.Text.Logic.dll`
1. `Microsoft.VisualStudio.Text.UI.Wpf.dll`
