### ISSUE TITLE
Exception label shouldn't stretch

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#53] opened 2015-08-07 11:18 UTC
![image](https://cloud.githubusercontent.com/assets/3845650/9134618/d89d4316-3cfd-11e5-8572-3f76f5a63f14.png)

Also I guess this badge should not stretch to multiple rows: 
![image](https://cloud.githubusercontent.com/assets/3845650/9134658/3df678ea-3cfe-11e5-93c9-21b0a015b423.png)

This is ReSharper 8.2.3 in VS 2013, I know it's not supported anymore but maybe this issue is not version-specific.

**Comment by MrJul** [comment] 2015-08-07 11:23
Duplicate of #33 (I'm currently implementing it!).
I will keep this issue open for the badge problem.

**Closed** 2015-08-07 19:01 UTC
Labels: bug
