### ISSUE TITLE
Doesn't show documentation for MessageBox.Show

### ISSUE THREAD

**Issue by NN---** [MrJul/ReSharper.EnhancedTooltip#111] opened 2017-04-20 18:04 UTC
Definition:
```cs
        /// <include file='doc\MessageBox.uex' path='docs/doc[@for="MessageBox.Show5"]/*' />
        /// <devdoc> 
        ///    <para>
        ///       Displays a message box with specified text. 
        ///    </para> 
        /// </devdoc>
        public static DialogResult Show(string text) { 
```

Tooltip
![](https://i.imgur.com/4nZLOTal.png)

**Comment by MrJul** [comment] 2017-08-25 11:58
I can't seem to reproduce this problem.
Enhanced Tooltip gets its documentation from ReSharper, which lookups documentation files.

Can you please verify that the following file exists on your system:
`%ProgramFiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework\<version>\System.Windows.Forms.xml`

**Comment by MrJul** [comment] 2017-12-20 18:11
Closing as I can't reproduce, please ensure that the XML file exists.
Don't hesitate to reopen with more information.

**Closed by MrJul** 2017-12-20 18:11 UTC
Labels: bug
