### ISSUE TITLE
duplicate tooltips after upgrade

### ISSUE THREAD

**Issue by robfazio** [MrJul/ReSharper.EnhancedTooltip#135] opened 2018-08-14 21:31 UTC
After upgrading VS to 15.8 and Resharper to 2018.1.4 I noticed that I now have both Reharper and ET tooltips, one under the other. Something must have changed in either VS 15.8 or Resharper 2018.1.4 because the tooltip design is also very different. It has a shaded box and inside it another darker box for each tooltip (see attached image below).

With ET enabled:
![image](https://user-images.githubusercontent.com/31356433/44119597-50ffb126-9fdf-11e8-93aa-842c48a037fc.png)

with ET disabled:

![image](https://user-images.githubusercontent.com/31356433/44119641-7600ce56-9fdf-11e8-9bc2-a485a1bce9a4.png)

again, this could very well be a R# bug or something that changed in 15.8 which causes the duplicate tooltips.

**Comment by robfazio** [comment] 2018-08-15 19:01
I am suspecting this is a Resharper bug because if you uninstall or disable Enhanced Tooltip, you would still get two tooltips. One from Resharper and one from VS.

and if you completely suspend Resharper, then you will only get the VS native tooltip.

**Comment by DimitarCC** [comment] 2018-08-15 19:02
Whatever it is i hope MrJul will fix it :)

**Comment by DimitarCC** [comment] 2018-08-15 19:14
Just for info i had Resharper 2018.1.4 with VS 15.7.6 and there were no problem with the tooltip. The problem came with upgrade to VS 15.8. So it must be some change in VS that does not comply with resharper or ET.

**Comment by robfazio** [comment] 2018-08-15 19:33
interesting...Thank you for clarifying that.

**Comment by DimitarCC** [comment] 2018-08-16 08:09
More info on this (if it is useful for somebody).....
The tooltips are duplicated because it renders the standard VS tooltip contents as well. They coming as Microsoft.VisualStudio.Text.Adornments.ContainerElement and are sorted out as vsUnknownContent. Thats why they are displayed. This problem exists in resharper as well. so Maybe that should be fixed by Resharper people.
About the strange styling....
It renders shaded box behind the tooltip because this is the original tooltip container. It seems it is added a new Microsoft.VisualStudio.Text.AdornmentLibrary.ToolTip.Implementation.WpfToolTipControl in 15.8 which is a container for ET. This control/container is not styled thats why it renders with default styles for Background, Border and Padding.

**Comment by iSchlicht** [comment] 2018-08-16 10:08
Have the same Problem.

**Comment by firstovandrey** [comment] 2018-08-16 13:31
I have this
![dublicate](https://user-images.githubusercontent.com/30042528/44211547-e16a0c00-a171-11e8-8a98-9d9bdea03a09.png)
![360](https://user-images.githubusercontent.com/30042528/44211550-e3cc6600-a171-11e8-8bdc-bf1e8be82007.PNG)
![2018](https://user-images.githubusercontent.com/30042528/44211551-e464fc80-a171-11e8-81db-0ae7272d818c.PNG)

**Comment by robfazio** [comment] 2018-08-16 17:57
UPDATE:
just spoke to a resharper engineer and they confirmed the problem is reproducible on their side and it is in fact caused by Resharper.
it is also possible that whatever fix they push may affect the ET plugin going forward (hopefully not).

**Comment by DimitarCC** [comment] 2018-08-17 10:54
Well meanwhile i have a fix for ET that fixes all of that issues. Ofcource its something like a hack thats why probably i didnt do it in right way that have to be done. but the result is 
![image](https://user-images.githubusercontent.com/1904901/44262820-11261c00-a225-11e8-9ae1-3564b0ea5634.png)

**Closed** 2018-09-12 12:51 UTC
Labels: bug

**Comment by Hirato** [comment] 2018-09-13 02:59
Just downloaded the new version for R# 2018.2 and VS 15.8.

I can confirm that C# isn't showing doubled up tooltips, however now that I have installed v3.7.0 of this extension, VB.NET code is.

![image](https://user-images.githubusercontent.com/881518/45464578-db9d2180-b743-11e8-91bb-2482d890098f.png)
